### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by RebelliousUno** [GoIV-Devs/GoIV#11]
JCenter has been deprecated, 

https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

Should migrate away from jcenter -> `mavenCentral()`

**Comment by RebelliousUno** [comment]
Looks like butterknife hasn't migrated away from jcenter to mavenCentral - Jcenter should be readonly atm at least

**Comment by lramati** [comment]
https://github.com/xZise/GoIV/issues/7
Is this issue relevant to this conversation?
(As an aside, I'm working on duplicating the relevant issues from that repo in this one)

**Comment by RebelliousUno** [comment]
Quite possibly, if it was possible to move away from butter knife then you could probably move away from jcenter completely.

**Comment by timoetzold** [comment]
butterknife is now on mavenCentral, but 'com.pavelsikun:material-seekbar-preference:2.3.0' isn't

**Comment by timoetzold** [comment]
done
