### ISSUE TITLE
Update minimum API to 24 (N)

### ISSUE THREAD

**Issue by timoetzold** [GoIV-Devs/GoIV#28]
Pokemon GO dropped support for Android 6, so we can as well.
https://niantic.helpshift.com/hc/en/6-pokemon-go/faq/3455-discontinued-support-for-android-6/

**Comment by lramati** [comment]
Is this meaningful to us?
Does dropping Android 6 support make our codebase simpler in any way?
If not, might make more sense to wait until a more relevant version is dropped by pokemon go

**Comment by timoetzold** [comment]
Yeah, there are 5 checks for `android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.N` which won't be needed anymore.
