### ISSUE TITLE
Update Target SDK to 30

### ISSUE THREAD

**Issue by RebelliousUno** [GoIV-Devs/GoIV#7]
Target SDK needs updating to 30 (Android 11) 
This is the latest version (currently) of Android so gives you access to the latest platform features and compatibility.
Min SDK version can stay where it is

**Comment by RebelliousUno** [comment]
https://developer.android.com/distribute/best-practices/develop/target-sdk
```Starting in November 2021, app updates will be required to target API level 30 or above and adjust for behavioral changes in Android 11. Existing apps that are not receiving updates are unaffected and can continue to be downloaded from the Play Store. Wear OS apps must continue to target API level 28 or higher.```

**Comment by timoetzold** [comment]
done
